#初始化数据

# 定义一个模块信息列表,结构为[{}{}..{}]
menus:
  - name: "菜单一"
    children: ["菜单一.一","菜单一.二","菜单一.三"]
  - name: "菜单二"
    children: ["菜单二.一","菜单二.二","菜单二.三"]
  - name: "系统管理"
    children: ["用户管理","角色管理"]

# 定义一个角色信息字典,用于构建初始化角色数据
default_role:
  # 角色名称
  name: "系统管理员"
  # 角色描述
  description: "全权限管理员角色"
  # 角色是否已删除
  is_deleted: False
  # 角色是否允许删除
  s_deletable: False

default_user:
  # 用户名称
  name: "系统管理员"
  # 用户手机号
  phone_num: "13335251675"
  # 账号
  username: "admin"
  # 密码
  password: "admin123"
  # 角色名称
  role_name: "系统管理员"
  # 是否已删除
  is_deleted: False
  # 是否可删除
  s_deletable: False